package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Projection rendering and two-way sync with source.

type Projection struct {
	Lens   LensConfig
	Blocks []ProjectionBlock
	Facts  []ProjectionFact
	// Sync is the projection-level sync policy: "view-only" (analytical lenses
	// that are regenerated, never written back) or "two-way" (extract lenses).
	Sync string
	// Extra holds additional projection files a single lens emits, e.g. the
	// control-flow lens emitting one file per branch. Each is rendered to its Path.
	Extra []ExtraFile
}

type ProjectionBlock struct {
	ID    string
	File  string
	Mode  string
	Tool  string
	Lines []string
	Facts []string
	Hash  string
	// LineOrigins maps individual projection lines back to scattered source
	// lines. Unlike SrcStart/SrcEnd, this supports analytical projections whose
	// editable surface is assembled from many files.
	LineOrigins []LineOrigin
	// LineGuards holds, per line, the branch conditions that must hold to reach it
	// (the unrolled-program "per-line assumptions"). In-memory only — never written
	// to the projection text or serialized.
	LineGuards [][]string `json:"-"`
	// Sync/Src fields support two-way "extract" blocks. SrcHash is the hash of
	// the source span at generation time; it lets SyncProjection detect whether
	// the source changed independently of the projection (conflict detection).
	Sync     string
	SrcFile  string
	SrcStart int
	SrcEnd   int
	SrcHash  string
}

type ProjectionFact struct {
	ID   string
	Text string
	Tool string
}

// finalizeProjection sorts blocks/facts and stamps content hashes. It recurses
// into Extra files (e.g. control-flow branches) so every emitted projection is
// stamped consistently.
func finalizeProjection(p *Projection, lens LensConfig) {
	if p.Sync == "" {
		p.Sync = "view-only"
	}
	SortProjection(p)
	for i := range p.Blocks {
		p.Blocks[i].Hash = hash(strings.Join(p.Blocks[i].Lines, "\n") + "\n")
	}
	for i := range p.Extra {
		p.Extra[i].Proj.Lens = lens
		finalizeProjection(&p.Extra[i].Proj, lens)
	}
}

func RenderProjection(path string, p Projection) error {
	var b strings.Builder
	body := projectionBody(p)
	sync := p.Sync
	if sync == "" {
		sync = "view-only"
	}
	fmt.Fprintf(&b, "# generated by file-projections\n")
	fmt.Fprintf(&b, "# lens: %s\n", p.Lens.Name)
	fmt.Fprintf(&b, "# analyzer: %s\n", p.Lens.Analyzer)
	fmt.Fprintf(&b, "# sync: %s\n", sync)
	fmt.Fprintf(&b, "# source-hash: %s\n", hash(body))
	fmt.Fprintf(&b, "# generated-at: %s\n\n", nowFunc().UTC().Format(time.RFC3339))
	b.WriteString(body)

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// projectionBody renders the stable, timestamp-free body (blocks + facts). The
// header carries the volatile generated-at; idempotency is defined over this body.
func projectionBody(p Projection) string {
	var b strings.Builder
	for _, block := range p.Blocks {
		b.WriteString(renderAnchor(block))
		b.WriteString("\n")
		for _, line := range block.Lines {
			b.WriteString(line)
			if !strings.HasSuffix(line, "\n") {
				b.WriteString("\n")
			}
		}
		b.WriteString("@@\n")
		for _, fact := range block.Facts {
			fmt.Fprintf(&b, "=> %s: %s\n", block.ID, fact)
		}
		for i, origin := range block.LineOrigins {
			if origin.SrcFile == "" || origin.Line <= 0 {
				continue
			}
			fmt.Fprintf(&b, "=> %s: origin %d src=%s:%d srchash=%s\n", block.ID, i+1, origin.SrcFile, origin.Line, origin.SrcHash)
		}
		b.WriteString("\n")
	}

	for _, fact := range p.Facts {
		if fact.Tool == "" {
			fmt.Fprintf(&b, "=> %s: %s\n", fact.ID, fact.Text)
		} else {
			fmt.Fprintf(&b, "=> %s.%s: %s\n", fact.Tool, fact.ID, fact.Text)
		}
	}
	if len(p.Facts) > 0 {
		b.WriteString("\n")
	}
	return b.String()
}

func SortProjection(p *Projection) {
	sort.SliceStable(p.Blocks, func(i, j int) bool {
		if p.Blocks[i].File == p.Blocks[j].File {
			return p.Blocks[i].ID < p.Blocks[j].ID
		}
		return p.Blocks[i].File < p.Blocks[j].File
	})
	sort.SliceStable(p.Facts, func(i, j int) bool { return p.Facts[i].ID < p.Facts[j].ID })
}

// searchMapProjection runs each labeled pattern via rg and emits a single sorted
// map block plus per-label count facts. Shared by entrypoints and exitpoints.
func searchMapProjection(cfg Config, lens LensConfig, patterns []labeledPattern, tool, mode string) (Projection, error) {
	root := lens.SourceRoot
	if root == "" {
		root = "."
	}
	type row struct {
		file  string
		line  int
		label string
		text  string
	}
	var rows []row
	for _, lp := range patterns {
		hits, err := ripgrep(cfg, lp.Regex, root)
		if err != nil {
			return Projection{}, fmt.Errorf("%s: pattern %q: %w", tool, lp.Label, err)
		}
		for _, h := range hits {
			rows = append(rows, row{h.File, h.Line, lp.Label, h.Text})
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].file != rows[j].file {
			return rows[i].file < rows[j].file
		}
		return rows[i].line < rows[j].line
	})
	// Default layout: exact code first, then the file:line locator in a padded second
	// column (meaning first, direction second). params.line_format overrides with
	// {file}/{line}/{label}/{code} placeholders for callers who want the regexp/label.
	tmpl := lens.Params["line_format"]
	var lines []string
	for _, r := range rows {
		if tmpl == "" {
			lines = append(lines, codeLoc(r.text, r.file, r.line))
		} else {
			lines = append(lines, formatRow(tmpl, r.file, r.line, r.label, r.text))
		}
	}
	if len(lines) == 0 {
		lines = append(lines, "// no matches under "+root)
	}
	p := Projection{Sync: "view-only"}
	p.Blocks = append(p.Blocks, ProjectionBlock{ID: mode, File: "model", Mode: mode, Tool: tool, Lines: lines})
	return p, nil
}

// makeBookmarkProjection builds a two-way bookmark over source span a-b. Shared by the
// bookmark analyzer and the single-line drop-in expander.
func makeBookmarkProjection(cfg Config, sourceRoot, file string, a, b int) (Projection, error) {
	path := filepath.Join(cfg.Root, sourceRoot, filepath.FromSlash(file))
	lines, err := readLines(path)
	if err != nil {
		return Projection{}, err
	}
	if a < 1 || b < a || b > len(lines) {
		return Projection{}, fmt.Errorf("bookmark: invalid line range %d-%d for %s (%d lines)", a, b, file, len(lines))
	}
	span := append([]string{}, lines[a-1:b]...)
	srcRel := filepath.ToSlash(filepath.Join(sourceRoot, file))
	p := Projection{Sync: "two-way"}
	p.Blocks = append(p.Blocks, ProjectionBlock{
		ID: fmt.Sprintf("%s:%d-%d", filepath.Base(file), a, b), File: file, Mode: "bookmark", Tool: "bookmark",
		Lines: span, Sync: "two-way", SrcFile: srcRel, SrcStart: a, SrcEnd: b, SrcHash: hash(strings.Join(span, "\n") + "\n"),
	})
	p.Facts = append(p.Facts, ProjectionFact{ID: "sync", Tool: "bookmark", Text: "two-way: edits inside the block sync back to source on `watch` or `sync`"})
	return p, nil
}

// ============================================================================
// Single-line drop-in bookmarks
// ============================================================================

// parseProjectionFile recovers blocks (with anchor metadata) from a rendered
// projection so the sync engine can detect edits and map them back to source.
func parseProjectionFile(path string) ([]ParsedBlock, error) {
	lines, err := readLines(path)
	if err != nil {
		return nil, err
	}
	var blocks []ParsedBlock
	for i := 0; i < len(lines); i++ {
		m := anchorRE.FindStringSubmatch(lines[i])
		if m == nil {
			continue
		}
		blk := ParsedBlock{Anchor: lines[i], File: m[1], ID: m[2], Tool: m[3], Mode: m[4], Hash: m[5]}
		if m[6] != "" {
			blk.Sync = "two-way"
			blk.SrcFile = m[6]
			blk.SrcStart = atoi(m[7])
			blk.SrcEnd = atoi(m[8])
			blk.SrcHash = m[9]
		}
		j := i + 1
		for j < len(lines) && lines[j] != "@@" {
			blk.Lines = append(blk.Lines, lines[j])
			j++
		}
		for k := j + 1; k < len(lines); k++ {
			if strings.HasPrefix(lines[k], "@@ ") {
				break
			}
			mm := originFactRE.FindStringSubmatch(lines[k])
			if mm == nil || mm[1] != blk.ID {
				if strings.TrimSpace(lines[k]) == "" {
					continue
				}
				continue
			}
			idx := atoi(mm[2])
			if idx <= 0 {
				continue
			}
			for len(blk.Origins) < idx {
				blk.Origins = append(blk.Origins, LineOrigin{})
			}
			blk.Origins[idx-1] = LineOrigin{SrcFile: mm[3], Line: atoi(mm[4]), SrcHash: mm[5]}
			blk.Sync = "two-way"
		}
		blocks = append(blocks, blk)
		i = j
	}
	return blocks, nil
}

// SyncProjection reconciles a two-way projection file with its source files. For
// each two-way block: if only the source changed, refresh the projection; if only
// the projection changed, write it back to source; if both changed, report a conflict.
func SyncProjection(cfg Config, projPath string) (SyncResult, error) {
	var res SyncResult
	blocks, err := parseProjectionFile(projPath)
	if err != nil {
		return res, err
	}
	// Group edits to source per file; apply with running offset for line-count drift.
	for _, blk := range blocks {
		if len(blk.Origins) > 0 {
			r, err := syncScatteredBlock(cfg, blk)
			if err != nil {
				return res, err
			}
			res.ToProjection += r.ToProjection
			res.ToSource += r.ToSource
			res.Conflicts = append(res.Conflicts, r.Conflicts...)
			continue
		}
		if blk.Sync != "two-way" || blk.SrcFile == "" {
			continue
		}
		srcPath := filepath.Join(cfg.Root, filepath.FromSlash(blk.SrcFile))
		srcLines, err := readLines(srcPath)
		if err != nil {
			return res, err
		}
		if blk.SrcStart < 1 || blk.SrcEnd > len(srcLines) || blk.SrcEnd < blk.SrcStart {
			res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s: stale range %d-%d", blk.SrcFile, blk.SrcStart, blk.SrcEnd))
			continue
		}
		liveSpan := srcLines[blk.SrcStart-1 : blk.SrcEnd]
		liveHash := hash(strings.Join(liveSpan, "\n") + "\n")
		projHash := hash(strings.Join(blk.Lines, "\n") + "\n")

		projEdited := projHash != blk.Hash
		srcChanged := liveHash != blk.SrcHash

		// Header retarget: the user edited the anchor's file/class (before #) or the a-b
		// range in the ID. Re-extract the view for the new target on save.
		wantFile, wantA, wantB := bookmarkTarget(cfg, blk)
		if wantFile != blk.SrcFile || wantA != blk.SrcStart || wantB != blk.SrcEnd {
			res.ToProjection++
			continue
		}

		switch {
		case projEdited && srcChanged:
			res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s#%s: both source and projection changed", blk.File, blk.ID))
		case projEdited && !srcChanged:
			// projection -> source
			newLines := append([]string{}, srcLines[:blk.SrcStart-1]...)
			newLines = append(newLines, blk.Lines...)
			newLines = append(newLines, srcLines[blk.SrcEnd:]...)
			if err := writeLines(srcPath, newLines); err != nil {
				return res, err
			}
			res.ToSource++
		case !projEdited && srcChanged:
			res.ToProjection++
		}
	}
	// If any source was updated or refreshed, rebuild the projection's two-way blocks
	// from current source so anchors (hash/srchash) are consistent again — this keeps
	// round-trips clean and works for both configured bookmarks and drop-ins (no lens).
	if res.ToSource > 0 || res.ToProjection > 0 {
		if err := refreshTwoWayProjection(cfg, projPath); err != nil {
			return res, err
		}
	}
	return res, nil
}

// refreshTwoWayProjection re-reads the source span of every two-way block in a projection
// and rewrites the file with consistent anchors. View-only blocks are preserved verbatim.
// Lens-independent, so it serves configured bookmark lenses and drop-in bookmarks alike.
func refreshTwoWayProjection(cfg Config, projPath string) error {
	name, analyzer, sync := readHeaderMeta(projPath)
	blocks, err := parseProjectionFile(projPath)
	if err != nil {
		return err
	}
	p := Projection{Sync: coalesce(sync, "two-way"), Lens: LensConfig{Name: name, Analyzer: coalesce(analyzer, "bookmark")}}
	for _, blk := range blocks {
		nb := ProjectionBlock{ID: blk.ID, File: blk.File, Tool: blk.Tool, Mode: blk.Mode, Lines: blk.Lines, Sync: blk.Sync}
		if len(blk.Origins) > 0 {
			nb.LineOrigins = make([]LineOrigin, 0, len(blk.Origins))
			nb.Lines = nb.Lines[:0]
			for _, origin := range blk.Origins {
				srcLines, err := readLines(filepath.Join(cfg.Root, filepath.FromSlash(origin.SrcFile)))
				if err != nil {
					return err
				}
				if origin.Line < 1 || origin.Line > len(srcLines) {
					nb.Lines = append(nb.Lines, "")
					nb.LineOrigins = append(nb.LineOrigins, origin)
					continue
				}
				line := srcLines[origin.Line-1]
				nb.Lines = append(nb.Lines, line)
				nb.LineOrigins = append(nb.LineOrigins, LineOrigin{SrcFile: origin.SrcFile, Line: origin.Line, SrcHash: hash(line + "\n")})
			}
			nb.Sync = "two-way"
		} else if blk.Sync == "two-way" && blk.SrcFile != "" {
			// The header (display file + ID range) is authoritative, so editing it retargets
			// the view. Fall back to the anchor's src= span when the header is unchanged.
			wantFile, wantA, wantB := bookmarkTarget(cfg, blk)
			srcLines, err := readLines(filepath.Join(cfg.Root, filepath.FromSlash(wantFile)))
			if err != nil {
				return err
			}
			if wantA >= 1 && wantB <= len(srcLines) && wantB >= wantA {
				span := append([]string{}, srcLines[wantA-1:wantB]...)
				nb.Lines = span
				nb.Sync = "two-way"
				nb.SrcFile = wantFile
				nb.SrcStart = wantA
				nb.SrcEnd = wantB
				nb.SrcHash = hash(strings.Join(span, "\n") + "\n")
				nb.ID = fmt.Sprintf("%s:%d-%d", filepath.Base(wantFile), wantA, wantB)
			}
		}
		p.Blocks = append(p.Blocks, nb)
	}
	finalizeProjection(&p, p.Lens)
	return RenderProjection(projPath, p)
}

func loadManifest(path string) map[string]string {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var m map[string]string
	if json.Unmarshal(b, &m) != nil {
		return nil
	}
	return m
}

func saveManifest(path string, m map[string]string) error {
	b, _ := json.MarshalIndent(m, "", "  ")
	return os.WriteFile(path, b, 0644)
}

// diffManifest reports files added, modified, and removed between two manifests.
func diffManifest(prev, cur map[string]string) (added, modified, removed []string) {
	for f, h := range cur {
		if ph, ok := prev[f]; !ok {
			added = append(added, f)
		} else if ph != h {
			modified = append(modified, f)
		}
	}
	for f := range prev {
		if _, ok := cur[f]; !ok {
			removed = append(removed, f)
		}
	}
	sort.Strings(added)
	sort.Strings(modified)
	sort.Strings(removed)
	return
}

// expandDropIns scans the projections dir for "drop-in" files — a freshly created
// .projection whose only content is a single `path/File.ext:line` (or `:a-b`) reference —
// and expands each in place into a full two-way bookmark with proper headers. Idempotent:
// once expanded the file has a header, so it is not matched again.
func expandDropIns(cfg Config) ([]string, error) {
	dir := filepath.Join(cfg.Root, cfg.ProjectionsDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var expanded []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".projection") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		ref, a, b, ok := parseDropIn(path)
		if !ok {
			continue
		}
		sourceRoot, rel, err := resolveSourceFile(cfg, ref)
		if err != nil {
			fmt.Fprintf(os.Stderr, "drop-in %s: %v\n", e.Name(), err)
			continue
		}
		proj, err := makeBookmarkProjection(cfg, sourceRoot, rel, a, b)
		if err != nil {
			fmt.Fprintf(os.Stderr, "drop-in %s: %v\n", e.Name(), err)
			continue
		}
		proj.Lens = LensConfig{Name: strings.TrimSuffix(e.Name(), ".projection"), Analyzer: "bookmark", SourceRoot: sourceRoot}
		finalizeProjection(&proj, proj.Lens)
		if err := RenderProjection(path, proj); err != nil {
			return expanded, err
		}
		expanded = append(expanded, path)
	}
	return expanded, nil
}

// parseDropIn returns the reference if the file's only meaningful content is a single
// `path:line` / `path:a-b` line (and it has no generated header yet).
func parseDropIn(path string) (ref string, a, b int, ok bool) {
	lines, err := readLines(path)
	if err != nil {
		return "", 0, 0, false
	}
	var content []string
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if t == "" {
			continue
		}
		if strings.HasPrefix(t, "#") || strings.HasPrefix(t, "@@") {
			return "", 0, 0, false // already a rendered projection
		}
		content = append(content, t)
	}
	if len(content) != 1 {
		return "", 0, 0, false
	}
	m := dropInRE.FindStringSubmatch(content[0])
	if m == nil {
		return "", 0, 0, false
	}
	a = atoi(m[2])
	b = a
	if m[3] != "" {
		b = atoi(m[3])
	}
	if b < a {
		a, b = b, a
	}
	return m[1], a, b, true
}

func syncScatteredBlock(cfg Config, blk ParsedBlock) (SyncResult, error) {
	var res SyncResult
	if len(blk.Origins) != len(blk.Lines) {
		res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s#%s: projection line count changed; scattered sync only supports one edited line per origin", blk.File, blk.ID))
		return res, nil
	}
	type change struct {
		line int
		text string
	}
	changes := map[string][]change{}
	for i, origin := range blk.Origins {
		if origin.SrcFile == "" || origin.Line <= 0 {
			res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s#%s line %d: missing origin", blk.File, blk.ID, i+1))
			continue
		}
		srcPath := filepath.Join(cfg.Root, filepath.FromSlash(origin.SrcFile))
		srcLines, err := readLines(srcPath)
		if err != nil {
			return res, err
		}
		if origin.Line > len(srcLines) {
			res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s:%d: stale origin", origin.SrcFile, origin.Line))
			continue
		}
		liveHash := hash(srcLines[origin.Line-1] + "\n")
		projHash := hash(blk.Lines[i] + "\n")
		projEdited := projHash != origin.SrcHash
		srcChanged := liveHash != origin.SrcHash
		switch {
		case projEdited && srcChanged:
			res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s:%d: both source and projection changed", origin.SrcFile, origin.Line))
		case projEdited && !srcChanged:
			changes[srcPath] = append(changes[srcPath], change{line: origin.Line, text: blk.Lines[i]})
		case !projEdited && srcChanged:
			res.ToProjection++
		}
	}
	for srcPath, cs := range changes {
		srcLines, err := readLines(srcPath)
		if err != nil {
			return res, err
		}
		for _, c := range cs {
			if c.line < 1 || c.line > len(srcLines) {
				res.Conflicts = append(res.Conflicts, fmt.Sprintf("%s:%d: stale origin", srcPath, c.line))
				continue
			}
			srcLines[c.line-1] = c.text
			res.ToSource++
		}
		if err := writeLines(srcPath, srcLines); err != nil {
			return res, err
		}
	}
	return res, nil
}

// FactByID returns the fact whose ID equals id, or the zero ProjectionFact and false.
func (p Projection) FactByID(id string) (ProjectionFact, bool) {
	for _, fact := range p.Facts {
		if fact.ID == id {
			return fact, true
		}
	}
	return ProjectionFact{}, false
}
